language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "nightly"  # currently points to 3.6-dev
# command to install dependencies
install:
  - pip install .
  - pip install pycodestyle
# command to run tests
script:
    - pycodestyle quaternions/quaternion.py
    - pycodestyle tests/test_quaternion.py
    - python setup.py test
